### ISSUE TITLE
读《富爸爸穷爸爸》的几点收获

### ISSUE THREAD

**Issue by scarsu** [scarsu/scarsu.com#6]
https://www.scarsu.com/rich_dad/

**Comment by scarsu** [comment]
sofa

**Comment by Qinhank** [comment]
`《【Javascript Event Loop & 异步机制】总结》`这篇好像评论不了呢

**Comment by scarsu** [comment]
> `《【Javascript Event Loop & 异步机制】总结》`这篇好像评论不了呢

Hi @Qinhank 
gitment需要creator初始化评论才能评论，你提到的那篇之前忘记初始化啦~现在已经初始化好了可以评论了。
